### ISSUE TITLE
Enhancement/Request: Possibility to have an Output/Screenshot for "Endless Notebook" pages

### ISSUE THREAD

**Issue by flanker0ne** [OpenKneeboard/OpenKneeboard#438] opened 2023-11-04 09:32 UTC
It will be a very nice feature, having the possibility to save the pages, tipically used as **_Endless Notebook_** like generic form or 9line 5line Checkin, for de-briefing purposes

**Comment by fredemmott** [comment] 2023-11-04 13:33
Closing as duplicate of #192

**Closed by fredemmott** 2023-11-04 13:33 UTC

**Comment by Burninator214** [comment] 2024-01-11 19:49
Very disappointing to not be added as a feature
