### ISSUE TITLE
D3D12: MSFS Crashes with DXDIAG Error Message during use of OpenKneeboard

### ISSUE THREAD

**Issue by Wassergeist** [OpenKneeboard/OpenKneeboard#682] opened 2024-11-03 09:01 UTC
While testing for Issue #681, I encountered a new issue.

I began a trace and launched the simulator with OpenKneeboard already running. At the moment I started VR mode in MSFS, the simulator (but not OpenKneeboard) crashed, displaying the following error:

![IMG_0616](https://private-user-images.githubusercontent.com/91049818/382509831-91049d71-e3d0-4201-86a7-a57b0c73568c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjA2OTEsIm5iZiI6MTczMDYyMDM5MSwicGF0aCI6Ii85MTA0OTgxOC8zODI1MDk4MzEtOTEwNDlkNzEtZTNkMC00MjAxLTg2YTctYTU3YjBjNzM1NjhjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA3NTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYTYwYzZlM2I1Nzg4YmZkOTAxNmJkYWI4Nzk4ZGRmM2RmMGE1NTc0MjM5NTdjZWVhN2RlNGM0MjgzZjczYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SnD29QEivS14blfvRpSZ1PtAQmSF2JUzVCASUwxwbGY)

  
I apologize for the photo quality—I had to use my phone since Windows didn’t switch to the pop-up window properly.

The error message displayed was: **DXDIAG\_ERROR\_DEVICE\_HUNG (0x997a0006)**.

I wanted to note that OpenKneeboard itself has never crashed, and all other flights on this day, when not using OpenKneeboard, ran smoothly. The only difference during the crash was whether OpenKneeboard was in use or not.

Previously, I encountered a similar issue with version 1.8.2 (which prompted me to upgrade to 1.9.10). At that time, however, the error code was slightly different: **DXDIAG\_ERROR\_INVALID\_CALL (0x887a0001)**.

I also found a report of a similar bug in the OpenKneeboard Discord channel, dated June 4th: "MSFS problem - CTD on every flight." Unfortunately, no definitive solution was posted there.

My setup closely matches another user’s setup mentioned in Discord:

*   **My setup**: Quest 3 on Virtual Desktop (VDXR), RTX 4090, Ryzen 7950X3D, latest drivers, and a Huion HS64 Tablet.
*   **His setup**: Quest 3 on Virtual Desktop (VDXR), RTX 4090, Ryzen 7950X3D, latest drivers, and an old Wacom Bamboo tablet with OpenTablet drivers.

Please find the trace attached. There is no dump file available as OpenKneeboard itself did not crash

 [trace (2).zip](https://github.com/user-attachments/files/17608482/trace.2.zip)

**Comment by fredemmott** [comment] 2024-11-04 14:43
Thanks, I'll see if I can figure this out before resolving D3D12 in #658 - while they're unrelated, #658 will require a complete rewrite of the D3D12 code, and it'd be good to understand what's going wrong before that.

That said, I'm generally not able to test with betas, and MSFS's D3D12 support is still in beta - you'll have the most reliable experience with D3D11.

**Comment by Wassergeist** [comment] 2024-11-04 16:20
Hey yes i know about D3D12. The Problem is some other stuff is running much smoother with 12.

If it is helpfull for you, I can do further troubleshooting. If yes I will try it again with D3D11 and 12 and will send you further traces.

**Comment by Wassergeist** [comment] 2024-11-21 06:57
@fredemmott because i was not able to get it running with D3D12 i switched back to D3D11. With that and the Canges in #681 i can use it know.

I plan to buy the new MSFS in December and as far as i know only D3D12 will be available there. If i Encounter Problems there, do you want to have more traces and Dump Files? Or do you have enough?

**Comment by fredemmott** [comment] 2024-11-22 16:08
Do you have dump files from the game, instead of from OpenKneeboard? Those would be the best way to narrow things down

**Comment by fredemmott** [comment] 2024-11-27 16:36
I've seen a few more reports of issues both with FS2024 and with D3D12 FS2020

I have a semi-reproducible crash thatwould only be when switching from VR to non-VR, restarting OpenKneeboard (not just show/hide), or when changing the number of views. I'll be digging into that.

However, the reports are all along the lines "I didn't do anything, it happens after a few minutes" - I'm not able to reproduce this, even after leaving things running for 45 minutes.

If you're comfortable with developer tools, one way to investigate this would be:
- install debugview or debugview++
- install 'graphics tools' from windows 'optional features' - this is *not* the same as "Turn windows features on or off'
- run dxcpl - this is part of the 'graphics tools' feature; do not install it from any other website
- Add MSFS in the 'scope' section
- Set the Direct3D/DXGI Debug Layer to 'force on'
- Mute info and warning messages
- Check that you get a *lot* of debug messages in debugview when MSFS is in VR; if you don't the debug layer is not working correctly
- Mute message 554 in the 'mute message ID' section of dxcpl, click apply
- Restart MSFS, wait for crash
- share the debug log

After this, dxcpl should look like this:

![image](https://github.com/user-attachments/assets/7dfc0d81-f794-4880-9130-12221866843d)

**Comment by Wassergeist** [comment] 2024-11-27 16:42
Hey @fredemmott 

iam not at home this week. When iam middle of next week, i will see into this.

As i wanted to have a "clean" System for MS2024 i resettend my PC. I hope i can reproduce everything. 
I didn't test OKB since then.

But i will report next week.

**Comment by Wassergeist** [comment] 2024-11-29 10:20
Good Morning @fredemmott 

I had an unexpected few minutes at home yesterday. I Checked FS2020 with DX12. I had two Crashes after some Minutes in the Sim. But i didn't get any Message. Just CTD's.

Now i am gone for the rest of the Weekend and Monday. When i am back next Week. I will see into your suggestions how to investigate the Problem. Hope i can help with this.

**Comment by fredemmott** [comment] 2024-11-30 01:03
Thanks for trying - if you're not seeing any messages (it should be *very* spammy until you mute 554), then you probably need to install https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/ as well

**Comment by Wassergeist** [comment] 2024-11-30 08:27
@fredemmott sorry for the misunderstanding. Had yesterday only very limited time, so was just confirming I have still the problem after resetting my pc. Just by running OKB and FS2020.

The message was regarding, that last time I got this direct x message after the crash. This message wasn't here this time.

I will do the troubleshooting with debug viewer next week.

**Comment by fredemmott** [comment] 2024-11-30 22:14
Latest one *may* fix the issue

**Comment by Wassergeist** [comment] 2024-12-02 22:31
Hi @fredemmott

i'm  back and i just tried it with the debugviewer. 

My findings. With Debugviewer on the Game is very laggy. If i close the Debugviewer the lags are gone.
Also with Debugviewer64 and DX12 FS2020 is crashing directly when reaching the Main Menu (with OKB on and off)

With debugviewer.exe (without 64) i can start a flight, but i get no Crash. OKB is working just fine, testet writing on the huion Tablet, switched Pages, Switchted Tabs, etc everything was just fine.

Only difference to my earlier Tries, are the DebugViewer and the dxcpl.

I tested it with  v1.8.12+gha.2381:

[DX11andDX12Test.zip](https://github.com/user-attachments/files/17984635/DX11andDX12Test.zip)

I will try to test the newest Version (should be this: https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/12099670533 ) and without the debugviewer if i will get a Crash with DX12.

Even if this is nothing i expected, i hope it will help you.

Greetings.

**Comment by Wassergeist** [comment] 2024-12-07 12:00
@fredemmott  Good Morning. 

Finally found some time to test.

I downloaded Version 1.8.14+gha.2483

Just finished a 1:30 hour flight in FS2020 in DX12 without any Problem.

It seems, at least for me, the bug is fixed (tested in FS2020 / DX12).

Thanks so much :-)

**Comment by fredemmott** [comment] 2024-12-07 15:09
Great, thanks, I'll close this out then.

Locking it too as there's some further major changes in D3D12 handling coming in the next update; they don't appear to cause issues, but if there are any further issues, it's time for them to be in separate issues.

**Closed by fredemmott** 2024-12-07 15:09 UTC
Labels: bug, needs more info
