### ISSUE TITLE
v1.9.4 crash - resuming on wrong thread

### ISSUE THREAD

**Issue by fr3nchy74** [OpenKneeboard/OpenKneeboard#660] opened 2024-09-12 05:10 UTC
... every 2 to 3 minutes :( Totally unusable.

[OpenKneeboardApp-crash-20240912T050719-21184.dmp](https://github.com/user-attachments/files/16973768/OpenKneeboardApp-crash-20240912T050719-21184.dmp)
[OpenKneeboardApp-crash-20240912T050719-21184.txt](https://github.com/user-attachments/files/16973769/OpenKneeboardApp-crash-20240912T050719-21184.txt)

**Comment by fredemmott** [comment] 2024-09-12 12:03
Are you doing anything with OpenKneeboard when it crashes, or does it crash when you just leave it completely alone?

**Comment by fredemmott** [comment] 2024-09-12 12:29
There should be a .msi download link at the bottom of https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/10830792564 in ~ 40 minutes ; could you try again with that, and share the new dmp/txt?

It will not fix the problem, but should provide more detail on the cause, or at least how to reproduce the problem.

**Comment by fredemmott** [comment] 2024-09-12 12:31
To go back to the stable version rather than the development/test version:
- uninstall v1.9
- restore your backup of saved games\openkneeboard if you made one
- otherwise, there should be one in `%LOCALAPPDATA%\OpenKneeboard\backups`
- install v1.8.10

The autoupdater may prompt you to update to v1.9.4 as you have previously installed a development/test version; skip all v1.9 versions unless you're happy to test.

**Comment by fredemmott** [comment] 2024-09-12 18:09
This is reasonably likely to be fixed by v1.9.6: https://github.com/OpenKneeboard/OpenKneeboard/releases/tag/v1.9.6

If not, can you attach a fresh crash dump/log from v1.9.6?

**Comment by fredemmott** [comment] 2024-09-13 10:53
Does it close itself , or some other definition of crash like stopping responding?

**Comment by fredemmott** [comment] 2024-09-13 14:10
If it freezes: https://openkneeboard.com/troubleshooting/crashes-and-freezes.html#getting-a-dump-file-for-a-freeze

If it crashes (closes itself): download and run https://github.com/OpenKneeboard/OpenKneeboard/blob/v1.8/scripts/enable-full-dumps.reg , then you should have a dump in `%LOCALAPPDATA%\CrashDumps` - windows creates this dump, so it *should* work even if OpenKneeboard's crash dumper fails.

If you're unable to get a dump via either method: https://openkneeboard.com/troubleshooting/logs-and-traces.html#standard-traces

**Comment by fr3nchy74** [comment] 2024-09-13 16:05
Yes it just closes itself. I’ll get you a dump file

**Comment by fr3nchy74** [comment] 2024-09-14 18:55
Unfortunately it didn't crash last night, but would not responds to the bindings ...

**Comment by fredemmott** [comment] 2024-09-14 19:52
Can you open a separate issue for that please, including:
- which bindings; device and bound action
- the debug logs

**Comment by fr3nchy74** [comment] 2024-09-15 01:22
Sorry I had to revert to 1.8.10 as I need it to work. But now, after replacing the settings by the ones I backup earlier, it crash on start :-(

[OpenKneeboard-20240915T012019.6923078-1.8.10.2238-9684.dmp](https://github.com/user-attachments/files/17004261/OpenKneeboard-20240915T012019.6923078-1.8.10.2238-9684.dmp)

**Comment by fredemmott** [comment] 2024-09-15 01:33
Please open a new issue for your new issue, including:
- a full dump - see https://openkneeboard.com/troubleshooting/crashes-and-freezes.html ; The dump you attached unfortunately contains no usable information.
- your settings backup

**Comment by fr3nchy74** [comment] 2024-09-15 02:05
Done. https://github.com/OpenKneeboard/OpenKneeboard/issues/664

**Comment by fr3nchy74** [comment] 2024-09-15 02:21
Ok, so back on 1.9.6 ... getting a crash when changing profile. I think there's already a ticket for that, but I can email you the file (link)

**Comment by fredemmott** [comment] 2024-09-15 02:49
If it's the same issue that others have reported, it's fixed by the MSI that can be downloaded at the bottom of https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/10864459342

If it's a different cause with the same symptoms - i.e. not fixed by that - a fresh set of dumps from that would be useful.

There are unlikely to be any *new* issues in that build compared to v1.9.6 - just the known issue seemed rare enough that it would be better to see if there are more issues in v1.9.6 before pushing out yet another update.

**Comment by fredemmott** [comment] 2024-09-16 20:33
If you're still encountering issues, please try with the latest prerelease instead, which is currently https://github.com/OpenKneeboard/OpenKneeboard/releases/tag/v1.9.8

**Comment by fredemmott** [comment] 2024-09-22 14:53
Closing - all issues reported in this thread have been fixed. If you encounter additional problems, please open a new issue.

**Closed by fredemmott** 2024-09-22 14:53 UTC
Labels: bug
