### ISSUE TITLE
CTD in Micrsoft Flight Simulator since updating to latest version...

### ISSUE THREAD

**Issue by thetford569** [OpenKneeboard/OpenKneeboard#526] opened 2024-03-11 00:33 UTC
I was getting CTDs when trying to center the view after entering VR.  I re-installed the latest version thinking the update was corrupt and it did fix that part however I was just flying and after a couple hours I got another CTD with this in the event viewer:

Faulting application name: FlightSimulator.exe, version: 1.37.7.0, time stamp: 0x00000000
Faulting module name: OpenKneeboard-OpenXR.dll, version: 1.7.0.1893, time stamp: 0x65e5f7be
Exception code: 0xc0000409
Fault offset: 0x000000000002d6a5
Faulting process id: 0x0x84C
Faulting application start time: 0x0x1DA733BFEBACF82
Faulting application path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.37.7.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Faulting module path: C:\Program Files\OpenKneeboard\bin\OpenKneeboard-OpenXR.dll
Report Id: ff402788-ecce-47bb-8d8d-6e8a5c12ca55
Faulting package full name: Microsoft.FlightSimulator_1.37.7.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by fredemmott** [comment] 2024-03-11 01:06
Do you have a .dmp file in %LOCALAPPDATA%\CrashDumps,
Or wherever MSFS usually saves crash dumps? Unfortunately the event log doesn’t ever contain enough information to be useful.

**Comment by fredemmott** [comment] 2024-03-11 01:15
If not, and you can reproduce this, OpenKneeboard's debug logs (accessible from the Help page) are likely to include more details.

**Comment by thetford569** [comment] 2024-03-11 01:56
Here is the crash dump files from MSFS and also Open Kneeboard.  I am going to put them in a folder and share them here as they are too large to attach....  There are 5 dumps from MSFS the latest one being after I repaired Open Kneeboard once I figured out that the first crashes were related to Open Kneeboard.  There are 2 .dmp files from Open Kneeboard itself.  I will try to reproduce.

Originally I updated Open Kneeboard as MSFS was being opened but it completed the update normally and I flew a flight yesterday just fine.  But then today I had those CTDs when I was trying to center the VR view upon going into VR mode in MSFS.  Every time I tried centering the view it crashed before I could load into the flight.  After doing a repair I was able to finally load in and fly but then after flying for awhile the sim crashed again and listed Open Kneeboard as a fault.  Just to give you some background info....

Also this is using the Sim Update 15 Beta version...

MSFS Crash Dumps - [https://1drv.ms/f/s!Ag_jgNx1a4E0hYGhWc9eiCNjkk9bonc?e=rMHJWT](url)

**Comment by fredemmott** [comment] 2024-03-11 02:05
Are you recentering with MSFS's in-game recentering, or with something in steamvr or your headsets' software?

It *looks* like MSFS is making an invalid OpenXR call, however:
- OpenKneeboard is turning "tell MSFS it's invalid" into a crash
- it's not 100% clear that it's actually MSFS.

The OpenKneeboard debug logs after a crash are almost essential.

**Comment by fredemmott** [comment] 2024-03-11 02:24
Also, thanks for the dumps :) as for the OpenKneeboard crashes:

- one is from 1.6.4
- the other is from 1.7.0 and appears to be an internal error in the windows app sdk when closing the app. There’s a new version of the windows app sdk which seems to fix it, but that’s too large a change for me to pull onto openkneeboard 1.7 , especially as it’s only crashing when quitting the app

**Comment by fredemmott** [comment] 2024-03-11 02:27
For my reference, it appears from the dump (can't tell for certain that there's nothing else without the OpenKneeboard logs):
- you're using WMR, so probably a G2
- you're using OpenXR Toolkit and the OpenXR OBS mirror layer

**Comment by thetford569** [comment] 2024-03-11 02:33
I uninstalled and reinstalled Open Kneeboard now to the latest version and I am going to try the flight again and see what happens.  I was also using sim rate to speed up the flight and this time I will either use that or possibly even teleport to the top of descent because it's late and I don't have much time but I wanted to complete this flight anyway.

**Comment by fredemmott** [comment] 2024-03-11 02:37
The version at https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/8226730777 will stop OpenKneeboard from turning this error into a crash, but I don’t know how MSFS will deal with this situation - it might crash, or it might recover fine.

**Comment by thetford569** [comment] 2024-03-11 02:49
I’ll let you know what happens.  I just updated to that version and will try a flight.Brandon ThetfordOn Mar 10, 2024, at 9:37 PM, Fred Emmott ***@***.***> wrote:﻿
The version at https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/8226730777 will stop OpenKneeboard from turning this error into a crash, but I don’t know how MSFS will deal with this situation - it might crash, or it might recover fine.

**Comment by thetford569** [comment] 2024-03-11 05:00
I was able to fly with your updated version without any issues.Brandon ThetfordOn Mar 10, 2024, at 9:37 PM, Fred Emmott ***@***.***> wrote:﻿
The version at https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/8226730777 will stop OpenKneeboard from turning this error into a crash, but I don’t know how MSFS will deal with this situation - it might crash, or it might recover fine.

**Comment by fr3nchy74** [comment] 2024-03-12 02:57
I have had similar issues with DCS since the latest update

![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/163084978/9066b080-943b-49f5-bc9c-8513c0b90af3)

**Comment by fredemmott** [comment] 2024-03-12 04:23
@fr3nchy74 if you have the same on 1.7.1, please open a separate issue with openkneeboard logs and crash dump from DCS. It is impossible to tell if it is the same problem from event viewer - the event viewer message boils down to “something went badly wrong”

**Comment by fredemmott** [comment] 2024-03-12 04:24
Issue from dump fixed in 1.7.1

**Closed by fredemmott** 2024-03-12 04:24 UTC
Labels: bug, question
