### ISSUE TITLE
Open Kneeboard Crashing after 20-30 minutes (.dmp attached)

### ISSUE THREAD

**Issue by SpectreBit** [OpenKneeboard/OpenKneeboard#383] opened 2023-07-24 02:44 UTC
From Discord (SpectreBit):

As the title says, my application always closes after awhile of having it open while playing DCS. I have to manually reopen it (assuming I even notice it's closed)

I am playing MT DCS in VR with a Varjo Aero if that makes any difference. Please help!

[TriggerModeMonitor.exe.4472.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/12141233/TriggerModeMonitor.exe.4472.zip)

**Comment by fredemmott** [comment] 2023-07-28 13:15
Can you attach a dump file for OpenKneeboard? The dump you've attached is for TriggerModeMonitor, which is from the MSI gaming app. You also might want to closing that app.

**Comment by SpectreBit** [comment] 2023-07-31 20:33
Does this work?
[OpenKneeboard-20230725T012553.4730390-1.4.4.1440-25116.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/12221947/OpenKneeboard-20230725T012553.4730390-1.4.4.1440-25116.zip)

**Closed** 2023-08-02 23:46 UTC

**Comment by fredemmott** [comment] 2023-08-02 23:48
It looks like this is happening when you change your 'mission specific' folder; this specific issue will be fixed in the version available from https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/5744896508 in 30-90 minutes when it's complete

If you have further crashes with that version (even if they're also when changing files in your mission-specific folder), please file another issue with a new dump :)

**Comment by fredemmott** [comment] 2023-08-02 23:48
Thanks for the dump and your patience - the full dump made it very clear where the problem is, though it is surpising.
