### ISSUE TITLE
v1.9.10 crash: coroutine resumed from wrong thread when switching profiles

### ISSUE THREAD

**Issue by Wassergeist** [OpenKneeboard/OpenKneeboard#681] opened 2024-10-29 18:01 UTC
OpenKneeboard Windows App Crashed during Profile Change even, if no Game is startet.  
  
This started to happen after Update to Version  v1.9.10+gha.2398  
  
Every Time i click on the Switch Profile Tab and choose a new Profile OKB is crashing. If i use it in a game it also crashes when iam using the Menu in the VR Kneeboard.  
  
But if i using my buttons on the Huion Tablet it crashes not every time.  
  
Please find attached the Debug Zip and the etl file:

**Comment by fredemmott** [comment] 2024-10-29 18:04
Can you share a crash dump?

https://openkneeboard.com/troubleshooting/crashes-and-freezes/

**Comment by fredemmott** [comment] 2024-10-29 18:04
Can you share a crash dump?

https://openkneeboard.com/troubleshooting/crashes-and-freezes/

**Comment by Wassergeist** [comment] 2024-10-29 18:04
I cannot upload here in github, will send a link in a few minutes.  
  
Sorry not sure why its not working here

**Comment by Wassergeist** [comment] 2024-10-29 21:45
Just for your Info, had suddenly a second problem.

I couldn't write in the endless notebook, only in files (one per tab) with my pen.

I uninstalled OpenKneeboard and installed it again. Now it seems to work again, so maybe just corrupted install or something.

**Comment by Yeti-UK** [comment] 2024-10-30 09:38
Similar happening since update. Crashes after a profile change.
[OpenKneeboardApp-crash-20241030T093101-2600.zip](https://github.com/user-attachments/files/17569289/OpenKneeboardApp-crash-20241030T093101-2600.zip)

**Comment by fredemmott** [comment] 2024-10-30 12:48
> Similar happening since update. Crashes after a profile change.
> 
> [OpenKneeboardApp-crash-20241030T093101-2600.zip](https://github.com/user-attachments/files/17569289/OpenKneeboardApp-crash-20241030T093101-2600.zip)
> 
> 

Please open a separate issue.

**Comment by fredemmott** [comment] 2024-10-30 13:07
@Wassergeist two issues for you, but neither is conclusive:

- at the time that dump was created, your installation was a mix of v1.8.2 and v1.9.10 - this is likely to cause problems
- go to 'user account control' and set the option at anything *except* the lowest. The lowest is misleading labelled - it automatically runs things as administrator even if you don't ask it to

Unfortunately the crash dump you put on google drive is empty (0 bytes); if you are still encountering issues after the reinstall:
- can you upload a new crash dump?
- the issue *may* already be fixed - can you try the version at https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/11390024711 ?

**Comment by fredemmott** [comment] 2024-10-30 13:09
`C:\Users\marcb\AppData\Local\CrashDumps\OpenKneeboardApp.exe.11384.dmp` and `C:\Users\marcb\AppData\Local\CrashDumps\OpenKneeboardApp.exe(1).11384.dmp` appear likely to include the required information to look into this further

**Comment by Wassergeist** [comment] 2024-10-30 13:17
@fredemmott 


> `C:\Users\marcb\AppData\Local\CrashDumps\OpenKneeboardApp.exe.11384.dmp` and `C:\Users\marcb\AppData\Local\CrashDumps\OpenKneeboardApp.exe(1).11384.dmp` appear likely to include the required information to look into this further

These files arent there. In the AppData\Local\OpenKneeboard Logs\Crashes dir i found one dmp file with 4MB from yesterday all others have 0KB.:

[OpenKneeboardApp-crash-20241029T173443-30788.dmp](https://github.com/user-attachments/files/17573189/OpenKneeboardApp-crash-20241029T173443-30788.dmp)

Sorry didnt realised that yesterday. 

I will try your suggested Build and will report back

**Comment by fredemmott** [comment] 2024-10-30 13:21
One of your other crashes (the debug zip contains the .txt files, but not the much larger dump files) shows switching profiles 7 times less than a second after starting OpenKneeboard, before it's fully initialized; while of course it's a bug if this makes OpenKneeboard crash, I'm curious how you're switching profiles, and if this repeated switching is intentional?

The 7 switches were between 'Default' and 'F18 One Knee'

**Comment by Wassergeist** [comment] 2024-10-30 13:27
No this was not intentional.

The Bug occured while i was clicking once on the Profile Name, then the List of all Profiles pop up and i choose the other. After i clicked once on the "new" profile OKB chrashed directly.

When i was using the Menu in Vr to Switch the same thing happend. 
But when i used the Buttons on the Graphic Tablet (i use the "action" exes not the binding in OKB) it worked almost every time and i was able to switch the profile.

**Comment by Wassergeist** [comment] 2024-10-30 13:37
@fredemmott 

Interessting find now:

When i reinstalled it yesterday i didnt had my old Profiles, everything was default.

No i removed OKB and installed the v1.9.11+gha.2452 version. Now i have my old profiles back, but also the bug is there again. And now i have a dmp file, in fact even two from the same second.

This is the Zip with the two dumps from now:
[OpenKneeboardApp-crash-20241030T132911-34092.zip](https://github.com/user-attachments/files/17573609/OpenKneeboardApp-crash-20241030T132911-34092.zip)

Maybe my Profiles are corrupted, because of that here are the settings folder zipped from C:\Users\marcb\AppData\Local\OpenKneeboard:

[Settings.zip](https://github.com/user-attachments/files/17573629/Settings.zip)

Maybe that will help you something

**Comment by Wassergeist** [comment] 2024-10-30 13:47
Of course here they are:

[OpenKneeboard-v1.9.11.2452-20241030T1447.zip](https://github.com/user-attachments/files/17573767/OpenKneeboard-v1.9.11.2452-20241030T1447.zip)

**Comment by fredemmott** [comment] 2024-10-30 13:58
Looks like you're encountering two different issues:

The 13:29:11 34092 crash is again showing you repeatedly switching between multiple profiles - in this case, 'Default' and 'MSFS', like the previous 'rapid switching' one I mentioned, this is showing windows raising a filesystem error when checking if your DCS saved games path exists

The 14:29:30 is the "Failed to enqueue coroutine resumption for the desired thread' one: I'm not seeing a cause here, so I suspect it may be the same root cause: it wants to resume on the main thread, but that thread may have already crashed - just not written the report yet

Unfortunately, the dumps aren't useful - not a problem on your end. If I can't figure out the problem, I'll at least see if I can figure out why the dumps are not containing the information I'd expect and see if I can fix that, so we get more information in a later build. I'll see if I can see anything in the debug zips.

Have you tried changing your UAC settings? This could be a permissions error on the saved games folder.

> When i reinstalled it yesterday i didnt had my old Profiles, everything was default.

The debug log shows you downgraded to v1.8.2, then to v1.8.12 again - you didn't reinstall v1.9.x. Older versions of OpenKneeboard can not use settings from newer versions, so v1.8 can't open settings from v1.9. That said, you should have backups of the v1.8 settings in `%LOCALAPPDATA%\OpenKneeboard\Backups`

**Comment by Wassergeist** [comment] 2024-10-30 14:19
The UAC Settings are one the lowest setting. I put it there shortly after i installed windows on the pc :-)  
  
Ok strange i defently had 19.10 installed.  
Nevermind.  
  
Yes i have the backups. And for me it would also be ok to "clean" the settingsfolder (i think i just have to empty the profiles folder and adjust the Profiles.json, or)  
  
But i can also wait for further instructions from you, to support you with the troubleshooting. Just like you want.

**Comment by fredemmott** [comment] 2024-10-30 14:22
> The UAC Settings are one the lowest setting. I put it there shortly after i installed windows on the pc :-)

> go to 'user account control' and set the option at anything *except* the lowest. The lowest is misleading labelled - it automatically runs things as administrator even if you don't ask it to

The lowest *will* cause problems.

**Comment by fredemmott** [comment] 2024-10-30 16:47
There's a *small* chance that the build at https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/11597787478 will fix the problem for you; if not, it should create more useful crash `.txt` files. Can you try, and repeat until you have a crash .txt file that mentions either 'exception' or 'std::terminate' in the first few lines?

For example, one of your recent crash txt files started with:

```
OpenKneeboardApp.exe (PID 34092) crashed at 20241030T132911

💀 FATAL: std::terminate() called
```

When you find one, could you attach all new .dmp and .txt files?

**Comment by fredemmott** [comment] 2024-10-30 17:52
> Just for our Info. I use a Hard Symlink to mount the \DCS folder under C:\users<userName>\Saved Games\ . I have the "real" Folder lying in my OneDrive for Backup Reasons and mount in via mklink /J in Saved Games. Maybe thats the Problem.

Yep, this is definitely the cause of some of your crashes, and is permissions related - not sure if onedrive, UAC (at the time the junction was created), a combination, or something else. 

While OpenKneeboard can be changed to not *crash*, it *will not* be changed to function with this setup - Windows is refusing to let OpenKneeboard look in that folder. It is impractical (and in some cases, impsosible) to change OpenKneeboard - and everything it depends on, including other windows components - to avoid using standard Windows and C++ filesystem features.

Alternatives include:
- remove the junction and move the entire saved games folder (not just DCS) from the saved games folder's properties page
- remove saved games\dcs, and use a launcher or CLI arguments to point the game directly at the location you want it to use

There's more details here: https://unit42.paloaltonetworks.com/junctions-windows-redirection-trust-mitigation/ - from that, it sounds like if a onedrive system service owns the folder, nothing can create a 'trusted' link to it.

If you choose to move the entire saved games folder, this is what you're looking for:

![image](https://github.com/user-attachments/assets/273f87ef-8fae-4a88-a0be-8c4c51babdd9)

---

I'll dig in to the profile switching one later, that appears to be a separate issue

**Comment by Wassergeist** [comment] 2024-10-30 18:36
Yeah I know about the other options. 

That's a thing I have to figure out on my side. But in the past everything worked just fine with this setup. Got all DCS readings etc, without any problem. Have this setup since years.

Also only the last build had the problem with the crash after the installation. But like mentioned no problem I will fix this on my side.

**Comment by fredemmott** [comment] 2024-10-30 18:45
The trace part of the debug logs show you were intermittently encountering the same problem on previous versions (including 1.8), it was just reported more generically (std::terminate).

**Comment by fredemmott** [comment] 2024-10-30 22:01
https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/11602311240 (1h again) will:
- not crash on that filesystem error; it will however still not be able to update the DCS hook lua in the situations when it would previously crash
- include more detailed information in the logs for the other crash

**Comment by Wassergeist** [comment] 2024-10-31 16:08
Sorry for the late Answer, was very busy today.

First Error: Crashing after Setup -> fixed
Second Error: Crashing by changing the profile:
Here are the new Dump Files:
[OpenKneeboardApp-crash-20241031T160357-10028-v1.9.11.2456.zip](https://github.com/user-attachments/files/17590168/OpenKneeboardApp-crash-20241031T160357-10028-v1.9.11.2456.zip)
[OpenKneeboard-v1.9.11.2456-20241031T1705.zip](https://github.com/user-attachments/files/17590172/OpenKneeboard-v1.9.11.2456-20241031T1705.zip)

**Comment by fredemmott** [comment] 2024-10-31 17:36
Notes to self:
- this is failing to resume in the UI thread
- there is no indication in the logs *why* it is failing to resume in the UI thread
- the coroutine in question ended by awaiting on a `winrt::apartment_context` (ie.. `co_await mUIThread;` or similar), which is unneeded with `task<>`, but this isn't a problem
- the log indicates this failed with RPC_E:SERVERFAULT

MSDN indicates:

> This method can return the standard return values E_INVALIDARG, E_OUTOFMEMORY, E_UNEXPECTED, and E_FAIL. If none of these failures occur, the return value of this function is the HRESULT value returned by the pfnCallback function.

This is inaccurrate or incomplete - the function can *only* return `S_OK`. I suspect that the coroutine resumption itself is throwing or having an exception - adding tracing to confirm.

**Comment by fredemmott** [comment] 2024-10-31 17:37
@Wassergeist thanks - can you:
- try https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/11616982802 once it's ready (again ~ 1h)
- collect an ETL trace again?

This again won't fix the issue, but adds more debugging information.

**Comment by Wassergeist** [comment] 2024-10-31 17:39
Yes no Problem, but iam Not at Home anymore. Will send the files tomorrow or tonight.

**Comment by Wassergeist** [comment] 2024-11-01 08:42
Good Morning. 

Please find attached everything i could think of.

At the first try (elt trace was running) the dmp file in AppData\Local\OpenKneeboard Logs\Crashes had only 0KB so i tried it multiple times, but every other time the dmp file was fine.
And one other find. In AppData\Local\CrashDumps for each crash there are two .dmp files. One called OpenKneeboardApp.exe.<differentNumber>.dmp and one OpenKneeboardApp.exe.<differentNumber>(1).dmp. I also attached these files.

The Files i will send, are all from the last try, also the elt trace. 
If you need more information, just let me know.

[OpenKneeboardApp-crash-20241101T083205-29912-openKneeboard_logs-Crashes.zip](https://github.com/user-attachments/files/17597786/OpenKneeboardApp-crash-20241101T083205-29912-openKneeboard_logs-Crashes.zip)
[OpenKneeboardApp.exe.204-appData-Local-CrashDumps.zip](https://github.com/user-attachments/files/17597795/OpenKneeboardApp.exe.204-appData-Local-CrashDumps.zip)
[OpenKneeboard-v1.9.11.2457-20241101T0934.zip](https://github.com/user-attachments/files/17597808/OpenKneeboard-v1.9.11.2457-20241101T0934.zip)
[trace-1.9.11.2457.zip](https://github.com/user-attachments/files/17597817/trace-1.9.11.2457.zip)

**Comment by fredemmott** [comment] 2024-11-01 13:51
Thanks, the trace is at least hinting where the problem lies:

> I suspect that the coroutine resumption itself is throwing or otherwise crashing - adding tracing to confirm.

Yep, this is what's happening - with the tracing from 7d8426c4625b6c8a90d19ff0a443f2b86baf9287, it shows that:
- the crash is after `TaskFinalAwaiter<>::resume_from_thread_pool()/ResumeCoro`, but there is no matching `TaskFinalAwaiter<>::resume_from_thread_pool()/CoroComplete`
- the crash is in the game injector thread, which is used for legacy oculus support, non-vr, and invasive wintab. It is not *meant* to be affected by profile changes, but clearly something is going wrong.

**Comment by fredemmott** [comment] 2024-11-01 15:00
- based on the *trace*, `WTSProcessEnumerateExW()` *may* be failing in an unexpected way. This is potentially UAC-related, but can be changed to 'try again later' instead of crashing
- based on the *dump*, the list of tabs might be removed or changed *while* `KneeboardView::GetTabIDs()` is in progress

Because threading and windows event loops are fun, either could be the cause of the other, or it could be two separate issues.

**Comment by fredemmott** [comment] 2024-11-01 15:13
Third issue - which I can reproduce:
- when switching between profiles...
- ... **AND** a tablet is used to switch profiles
- ... **AND** the two profiles have a differing number of views

... this `fatal()` check is triggered:

https://github.com/OpenKneeboard/OpenKneeboard/blob/900a057f0732d38bbb137e59b511440eecad73a3/src/app/app-common/KneeboardState.cpp#L156-L164

**Comment by fredemmott** [comment] 2024-11-01 16:41
@Wassergeist https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/11632893966 should fix all 3 of those, and hopefully fixes things for you.

If so, can you please collect and share a trace when switching profiles a few times anyway? It would be useful to confirm some suspicions I had and to help avoid future issues.

If you're still encountering problems, both a trace and a dump would be useful again - thanks for all the info last time :)

**Comment by Wassergeist** [comment] 2024-11-01 17:19
@fredemmott tried it, but no joy.

Same Crashes. Please find attached all files:

[OpenKneeboardApp-crash-20241101T171413-9468-openkneeboardLog-Crashes.zip](https://github.com/user-attachments/files/17602459/OpenKneeboardApp-crash-20241101T171413-9468-openkneeboardLog-Crashes.zip)
[OpenKneeboardApp.exe.9468-appdata-local-crashDumps.zip](https://github.com/user-attachments/files/17602468/OpenKneeboardApp.exe.9468-appdata-local-crashDumps.zip)
[trace-1.9.11.2458.zip](https://github.com/user-attachments/files/17602476/trace-1.9.11.2458.zip)
[OpenKneeboard-v1.9.11.2458-20241101T1817.zip](https://github.com/user-attachments/files/17602477/OpenKneeboard-v1.9.11.2458-20241101T1817.zip)

**Comment by fredemmott** [comment] 2024-11-01 17:51
That's a new issue, showing what appears to be a bug in the Windows PDF library
- are you still having *reliable* crashes when switching profiles?
- either way, can you share another set of dumps for another time it crashes?

**Comment by Wassergeist** [comment] 2024-11-01 21:52
Hey ok it seems im not lucky with that :-)

I did some testing:

1.  Yes i get still reliable crashes when switching profiles. Every time, not once without Crashing.
2.  I tried to use OKB in MSFS for a flight. As long as i dont interact with it, it seems to be fine. But if i start to try to write something on my Huion Tablet i find two issues:
      - I cannot write on a Endless Notebook Tab, only on "normal" file tabs
      - After a few seconds of interacting OKB is crashing
3. When i rename the settings folder to settings_backup and start OKB again, it has 2 Profiles. The Default one and the last i used in the "old" settings Folder. (OKB creates a new Settings folder)
    With this new Settings folder i can switch without any problem. (MSFS Profile has 3 tabs und the Default has more  than 3 tabs)
    When i delete the new settings Folder and rename the settings_backup back to settings and restart OKB. The Crashes during profile switching are back.
    
Error 2 happend with the "original" settings folder which has problems with the profile switching. I hadn't time to test it with the "new default" settings folder.
    
    
I have no idea if this is all symptoms of one big Problem or if these are Independent Errors.

I tried to gather as much data as i can. (The Trace file for the crash during the use, is to big for github. I put in on my google Drive.

I can also understand if you say i should just use a new settings folder, but iam also happy to help you further with the troubleshooting and keep the "faulty" settingsfolder.

Files for crash during use:
Trace-File: [https://drive.google.com/drive/folders/1FuwsY4c8OZUTx-OIFRgp-H_lglnZRgAt?usp=sharing](https://drive.google.com/drive/folders/1FuwsY4c8OZUTx-OIFRgp-H_lglnZRgAt?usp=sharing)
Dump: [OpenKneeboardApp-crash-20241101T184853-6676-Crash-during-use-in-msfs.zip](https://github.com/user-attachments/files/17604402/OpenKneeboardApp-crash-20241101T184853-6676-Crash-during-use-in-msfs.zip)

Files for crashing during profile-switching:
Trace-File: [trace-crash-at-profile-switch.zip](https://github.com/user-attachments/files/17604404/trace-crash-at-profile-switch.zip)
Dump: [OpenKneeboardApp-crash-20241101T213121-27008-crash-at-profile-switch.zip](https://github.com/user-attachments/files/17604406/OpenKneeboardApp-crash-20241101T213121-27008-crash-at-profile-switch.zip)

Files for "normal" operation with "new" settings folder:
Trace-File: [trace-with-new-settings-folder.zip](https://github.com/user-attachments/files/17604410/trace-with-new-settings-folder.zip)


Debug-Zip file gatherd after last crash during profile-switch and before testing with "new" settings Folder:
[OpenKneeboard-v1.9.11.2458-20241101T2233-after-crash-at-profile-switch.zip](https://github.com/user-attachments/files/17604416/OpenKneeboard-v1.9.11.2458-20241101T2233-after-crash-at-profile-switch.zip)

Hope this helps

**Comment by Wassergeist** [comment] 2024-11-02 21:53
@fredemmott like i wrote, yesterday i wasnt able to test interacting with the "new" default settings folder. 

After i did today some flight ins MSFS VR without OpenKneeboard, i just startet a trace and went into the Simulator. In the Moment i startet the VR Mode in MSFS, MSFS crashed with the following error:

![IMG_0616](https://github.com/user-attachments/assets/91049d71-e3d0-4201-86a7-a57b0c73568c)
(sorry was only able to take a photo by phone, because Windows didnt switch to this)

OpenKneeboard never Crashed. And all other Flights on this day, without OpenKneeboard worked fine. Only differnce was using OKB or not.

I had this before with 1.8.2 (before i updated to 1.9.10 in the first place, in fact this was the reason i upgraded)

I did also find a similar bug in your discord. "MSFS problem - CTD on every flight." from the June-04. But there was no final answer to this problem

My Setup is also almost identical to the guy in Discord:
My Setup: Quest 3 on Virtual Desktop / VDXR, 4090, 7950X3D, latest drivers. Huion HS64 Tablet
His Setup: Quest 3 on Virtual Desktop / VDXR, 4090, 7950X3D, latest drivers. Old Wacom Bamboo with OpenTablet driver

Iam not sure if this is related to all the other Stuff or not, but since i have a trace file, I thought i will send it to you:
[trace (2).zip](https://github.com/user-attachments/files/17608482/trace.2.zip)


If this is not related, should i open a new issue?

**Comment by fredemmott** [comment] 2024-11-02 22:25
Thanks - yep, could you open a separate issue? To manage things, I really need a separate github issue (or discord thread) per set of circumstances, including what crashes, when, and for whom.

This is almost certainly unrelated to the prior MSFS issue, unless it is a bug in the MSFS D3D12 Beta rather than OpenKneeboard's D3D12 support as OpenKneeboard's D3D12 has been completely rewritten in v1.9, with nearly no common principles.

**Comment by Wassergeist** [comment] 2024-11-21 06:54
@fredemmott I was able to use OKB again without Problem.

For that i removed all OKB folders from AppData, uninstalled the last Version i got from you and installed the latest stable Version. No it seems fine. 

Maybe it was just a corrupted settings folder.

But thanks again for your amazing help.

**Comment by fredemmott** [comment] 2024-11-26 17:34
Could you share a debug zip with the new settings folder?

**Comment by Wassergeist** [comment] 2024-11-27 16:42
Hey @fredemmott as wirtten in the other Issue.

iam not at home this week. When iam middle of next week, i will see into this.

As i wanted to have a "clean" System for MS2024 i resettend my PC. I hope i can reproduce everything. 
I didn't test OKB since then.

But i will report back next week.

**Comment by Wassergeist** [comment] 2024-12-07 12:01
@fredemmott  Good Morning.

here is the Debug Zip from Version 1.8.14. No issues to switch Profiles:

[OpenKneeboard-v1.8.14.2483-2024-12-07-13-00.zip](https://github.com/user-attachments/files/18048245/OpenKneeboard-v1.8.14.2483-2024-12-07-13-00.zip)

**Comment by fredemmott** [comment] 2024-12-07 16:45
Thanks; v1.8 would be more likely to have things quietly and subtly go wrong after a large amount of time, so doesn't really inform this.

Going to close this as there's already been a lot of issues fixed here (though with similar visible symptoms), and they're exclusive to the v1.9 branch. If you encounter further problems, please open a new issue.

**Closed by fredemmott** 2024-12-07 16:45 UTC
Labels: bug, needs more info
