### ISSUE TITLE
OpenKneeboard Stopped working in the latest DCS update v2.9.0

### ISSUE THREAD

**Issue by hellion102** [OpenKneeboard/OpenKneeboard#426] opened 2023-10-21 03:23 UTC
### Discussed in https://github.com/OpenKneeboard/OpenKneeboard/discussions/425

<div type='discussions-op-text'>

<sup>Originally posted by **hellion102** October 20, 2023</sup>
My version of DCS got updated today to v2.9.0

I noticed that OpenKneeboard overlay is no longer working (showing up as an overlay in DCS) anymore.
I do have DCS's game paths added in OpenKneeboard's game paths as before with both the multi-threading and non-multithreading paths registered.
Also run both DCS and OpenKneeboard in Windows Administrator modes as well.

Does anyone else have this problem, and hopefully there is a solution?

Thanks!
:)
</div>

**Comment by fredemmott** [comment] 2023-10-21 09:12
OpenKneeboard supports v2.9.

Closing as duplicate of #425.

**Closed by fredemmott** 2023-10-21 09:12 UTC
