### ISSUE TITLE
Feature Request: Separate position of zoomed kneeboard

### ISSUE THREAD

**Issue by Titanex7** [OpenKneeboard/OpenKneeboard#437] opened 2023-11-01 18:39 UTC
I would like to be able to set different position data for the zoomed window than for the normal window or an offset (hor./vert.).
I use the kneeboard quite low in the cockpit and the zoomed view requires me to tilt my head down too much.

**Comment by fredemmott** [comment] 2023-11-01 20:03
Duplicate of #149, with #236 related but not the same

**Closed by fredemmott** 2023-11-01 20:03 UTC
