### ISSUE TITLE
Switch Kneeboard cycles input and app, no longer switches first two kneeboard states in VR

### ISSUE THREAD

**Issue by LtJaeger** [OpenKneeboard/OpenKneeboard#489] opened 2024-02-03 08:48 UTC
in v1.7a8 the switch kneeboard command has no effect

**Comment by fredemmott** [comment] 2024-02-04 03:17
I'm unable to reproduce this; can you share the debug logs, and how you are attempting to switch the kneeboard? Both the bindings and the remote still work here.

**Comment by LtJaeger** [comment] 2024-02-04 10:36
[OpenKneeboard-v1.7.0.1804-2024-02-04-11-33.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/14156370/OpenKneeboard-v1.7.0.1804-2024-02-04-11-33.zip)

I checked the binding, it is OK. I see a flicker on the 2d view, but the view in 3d doesnt change. File attached

**Comment by fredemmott** [comment] 2024-02-04 13:01
A few related things:
- [ ] it should be possible to cycle input and the app between all views, not just the first two. This is what it currently does, but it should be a separate thing
- [ ] Swapping the first two is handy for actual kneeboards, but the concept of a binding doesn’t  scale to >2. Binding should special case first two, remote control could take options 
- [ ] currently only the first view is marked as non-VR capable, as the non-VR renderer can only draw one. All should be, though it’s not clear how cycle input/swap should relate here.

**Comment by fredemmott** [comment] 2024-02-04 13:07
There’s also #155 which fits in here, and would probably be good to address first, as it would make it make sense to address nonVR the same way as VR

**Closed** 2024-02-04 15:28 UTC
Labels: bug
