### ISSUE TITLE
Ability to create switchable profiles in game

### ISSUE THREAD

**Issue by klinkeye** [OpenKneeboard/OpenKneeboard#169] opened 2022-09-02 01:37 UTC
To have several defined profiles which each profile contains a group of tabs that can be called and switched ingame.
A general use case would be for a day kneeboard used until night conditions set in and be able to switch to a night set which I create with lower white levels as well as different pages such as CASE II or III recoveries vs CASE I for daytime good visibility conditions.

**Comment by fredemmott** [comment] 2022-09-02 14:59
Thanks for the suggestion! I'm closing this as it's a duplicate of #63

**Closed by fredemmott** 2022-09-02 14:59 UTC

**Comment by klinkeye** [comment] 2022-09-13 05:25
I dont quite agree that its a duplicate. That request was regarding the settings of the application. I am talking about profiles which change the content of the kneeboards. However if you dont want to consider this, I respect your decision.
