### ISSUE TITLE
Add a folder in 1.2beta5..3 causes crash

### ISSUE THREAD

**Issue by dmeador** [OpenKneeboard/OpenKneeboard#178] opened 2022-09-07 05:23 UTC
I started with OpenKneeboard 1.1.4.
I added a folder with PDFs in v 1.1.4.  I could not see the PDFs in the folder.  I upgraded to 1.2 beta3, and got a crash immediately upon starting the OpenKneeboard app.  To fix, I uninstalled 1.2beta3.  Reinstalled 1.1.4. Then deleted the folder.  Then I was able to upgrade to 1.2 beta, and it the app loaded ok.  However, upon adding the folder (with some PDFs) it started crashing again.  A faster workaround to avoid uninstalling is to rename the folder to some other name, which allows 1.2beta5 to load again.

**Comment by fredemmott** [comment] 2022-09-07 13:59
I can't reproduce this; could you share the PDFs you're using, and any recent OpenKneeboard `.dmp` files either in `Saved Games\OpenKneeboard` or `%LOCALAPPDATA%\CrashDumps` ?

> v1.1.4 I could not see the PDfs in the folder

This is expected; PDFs in folders are a new feature in v1.2-beta3

**Comment by fredemmott** [comment] 2022-09-07 14:03
Also, does it crash if you add go to tabs -> add -> 'files (single per tab)' and select every file in the folder?

**Comment by dmeador** [comment] 2022-09-07 21:07
Successful if I add all single per tab.  [Attaching a zip of the folder w/ pdf files](https://1drv.ms/u/s!AvEikYaasAdltiono0aoqMW09_8-?e=XbyMbs) (<-- here)  I am using.

**Comment by fredemmott** [comment] 2022-09-08 01:35
Oh this is fun, I can reproduce in Release builds but not Debug builds

**Comment by fredemmott** [comment] 2022-09-08 02:23
Next question is *why* they're destroyed while loading...

**Comment by fredemmott** [comment] 2022-09-08 03:08
@dmeador there should be a .msix download at the bottom of https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/3012186240 when it's finished (probably 15-45 minutes) - could you give that a try?

**Comment by dmeador** [comment] 2022-09-08 03:30
Ah the old friend “breaks in release and not debug”.   If I only had a nickel for every time that happened to me….  Perhaps an uninitialized variable being used as stack garbage in release, but memory is initialized or different in debug. ;-)

**Comment by dmeador** [comment] 2022-09-08 03:46
Works not, but I get the following error on load.  Maybe this will be fixed in full rebuild.
![image](https://user-images.githubusercontent.com/15837982/189029670-a3354789-9133-4d78-a508-bc0426da2630.png)

**Comment by fredemmott** [comment] 2022-09-08 04:01
Thanks, closing this then; the other issue is unrelated (changing windows sdk and windows app sdk versions to try and workaround some bugs there, apparently changes MSIX sandboxing behavior) and reliably repros - won’t be left in for long :)

**Closed by fredemmott** 2022-09-08 04:01 UTC
Labels: bug, question

**Comment by fredemmott** [comment] 2022-09-08 13:26
@dmeador on my system, it appears that error was that the PDF-related crashes happened while the OpenXR-Helper subprocess was running; this left a zombie process - that annoyingly doesn't show up in task manager, or resource monitor (whether searching for that process or 'What process has this file open?').

On windows, you can't modify/delete/rename an exe or DLL that is running, so that blocks this sync

To check:
1. open up `C:\ProgramData\OpenKneeboard` in explorer
2. try to delete `OpenKneeboard-OpenXR-Helper.exe`
3. it should give you an in-use dialog which may say which process has it open
4. if it doesn't say which process, try `Get-Process -Name "*OpenKneeboard-OpenXR*'` in powershell

To fix:
* easy mode: reboot
* hard mode: open powershell, `Get-Process -Name "*OpenKneeboard-OpenXR*" | Stop-Process`
