### ISSUE TITLE
Suggestion: Adding profiles based on another profile besides default

### ISSUE THREAD

**Issue by otherguy485** [OpenKneeboard/OpenKneeboard#709] opened 2024-12-21 04:08 UTC
I would like the ability to chose which existing profile to use as the template when adding a new profile.

Right now I have profiles for several cars and some of them are very similar to each other with minor tweaks.
when I create a new profile it uses the default which requires more editing/moving than if I were able to select something already created that is closer to what I want.

**Comment by fredemmott** [comment] 2024-12-21 05:32
Duplicate of #537

**Closed by fredemmott** 2024-12-21 05:32 UTC
