### ISSUE TITLE
Zoomed KB Does Not Resume Default Size

### ISSUE THREAD

**Issue by jspencer46** [OpenKneeboard/OpenKneeboard#712] opened 2024-12-24 13:07 UTC
DCS 2.9.10.4160; Open Kneeboard 1.8; Win 11; RTS 4090; OpenXR; VR BigScreen Beyond. Occasionally the zoomed Kneeboard will not return to default size when diverting gaze away from it.

**Comment by fredemmott** [comment] 2024-12-31 16:45
Dupe of discord thread, waiting for more info there.

**Closed by fredemmott** 2024-12-31 16:45 UTC
