### ISSUE TITLE
Bug: First page loop does not work

### ISSUE THREAD

**Issue by OR-WS** [OpenKneeboard/OpenKneeboard#246] opened 2023-01-14 22:42 UTC
In version 1.3, in 2D, even though last page/first page loop is enabled, last page forward loop works but first page backward loop does not.

Last tab/first tab looping works fine.

**Comment by fredemmott** [comment] 2023-01-15 00:22
I'm not able to reproduce this; are you seeing it on every tab, or just some specific tab?

**Comment by OR-WS** [comment] 2023-01-15 10:53
> I'm not able to reproduce this; are you seeing it on every tab, or just some specific tab?

Curious. It seems fixed with v1.3.1.

**Comment by fredemmott** [comment] 2023-01-21 12:31
Closing for now; the changes in v1.3.1 don't seem related, but for now at least, there's no way for me to act on this.

**Closed by fredemmott** 2023-01-21 12:31 UTC
Labels: question
