### ISSUE TITLE
OK crashes with window captures for app on secondary screens. 

### ISSUE THREAD

**Issue by SPAS79** [OpenKneeboard/OpenKneeboard#278] opened 2023-02-23 14:11 UTC
CTD when deleting "windows capture" tab if the tab is on a secondary monitor.

This started in v1.3.x, OK would crash on start if any of the applications/windows for the "window capture" tabs were on secondary screens (connected to the same GPU). No crash if the windows do not exist and/or are on primary monitor when added or when OK launches. 

Windows can then be moved to secondary monitors with no issues (OK then runs fine).

V1.4.b1/b2 somewhat changed behavior as follows:
OK does not crash and launches normally if a window capture for an app that is on a secondary screen is set up, but it does not capture the app either (the tab is present but empty). If I try to delete the tab, OK crashes. On restart the tab is deleted and can be recreated but will not display until OK starts with the tab on the main windows screen. 

Behavior was observed with firefox and discord capture tabs.

**Comment by fredemmott** [comment] 2023-02-25 01:38
I'm not able to reproduce this; could you share a dump file? see https://openkneeboard.com/troubleshooting/crashes-and-freezes.html

**Comment by fredemmott** [comment] 2023-06-17 15:37
Closing: no other reports, and unable to reproduce. I'm unable to investigate this without a dump file (see https://openkneeboard.com/troubleshooting/crashes-and-freezes.html ) or a way to reproduce the problem.

**Closed by fredemmott** 2023-06-17 15:37 UTC
Labels: bug, question
